// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQt8yk1rJfMpB3bj4gEHARCcjbES90o7Y',
    appId: '1:645680321182:web:d5acddc2d36e34360fa18f',
    messagingSenderId: '645680321182',
    projectId: 'pushnotification-b8aaf',
    authDomain: 'pushnotification-b8aaf.firebaseapp.com',
    storageBucket: 'pushnotification-b8aaf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtyjsDoi-1ytDGByi3rhc_trKd7ydgODc',
    appId: '1:645680321182:android:803755bc0103bd200fa18f',
    messagingSenderId: '645680321182',
    projectId: 'pushnotification-b8aaf',
    storageBucket: 'pushnotification-b8aaf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs0erR--Z-sYPIc4dzvakThWXaUasXRPc',
    appId: '1:645680321182:ios:301e9995eb8e9c6e0fa18f',
    messagingSenderId: '645680321182',
    projectId: 'pushnotification-b8aaf',
    storageBucket: 'pushnotification-b8aaf.firebasestorage.app',
    iosBundleId: 'com.example.loginPortal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs0erR--Z-sYPIc4dzvakThWXaUasXRPc',
    appId: '1:645680321182:ios:301e9995eb8e9c6e0fa18f',
    messagingSenderId: '645680321182',
    projectId: 'pushnotification-b8aaf',
    storageBucket: 'pushnotification-b8aaf.firebasestorage.app',
    iosBundleId: 'com.example.loginPortal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQt8yk1rJfMpB3bj4gEHARCcjbES90o7Y',
    appId: '1:645680321182:web:71aae57b50e9e10c0fa18f',
    messagingSenderId: '645680321182',
    projectId: 'pushnotification-b8aaf',
    authDomain: 'pushnotification-b8aaf.firebaseapp.com',
    storageBucket: 'pushnotification-b8aaf.firebasestorage.app',
  );
}
